//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainApp.ServiceReferenceLecteur {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BIB_AllLibelle_Result", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class BIB_AllLibelle_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BIB_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BIB_LibelleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BIB_ID {
            get {
                return this.BIB_IDField;
            }
            set {
                if ((this.BIB_IDField.Equals(value) != true)) {
                    this.BIB_IDField = value;
                    this.RaisePropertyChanged("BIB_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BIB_Libelle {
            get {
                return this.BIB_LibelleField;
            }
            set {
                if ((object.ReferenceEquals(this.BIB_LibelleField, value) != true)) {
                    this.BIB_LibelleField = value;
                    this.RaisePropertyChanged("BIB_Libelle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LEC_Login_Result", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class LEC_Login_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LEC_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LEC_UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LEC_Id {
            get {
                return this.LEC_IdField;
            }
            set {
                if ((this.LEC_IdField.Equals(value) != true)) {
                    this.LEC_IdField = value;
                    this.RaisePropertyChanged("LEC_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LEC_UserName {
            get {
                return this.LEC_UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LEC_UserNameField, value) != true)) {
                    this.LEC_UserNameField = value;
                    this.RaisePropertyChanged("LEC_UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EMP_AllEmpruntsRenduByLEC_Id_Result", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class EMP_AllEmpruntsRenduByLEC_Id_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BibliothèqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_d_empruntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EMP_DateRetourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> EMP_MontantPayeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExemplaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Exemplaire
        {
            get
            {
                return this.ExemplaireField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExemplaireField, value) != true))
                {
                    this.ExemplaireField = value;
                    this.RaisePropertyChanged("Exemplaire");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre
        {
            get
            {
                return this.TitreField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TitreField, value) != true))
                {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bibliothèque
        {
            get
            {
                return this.BibliothèqueField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BibliothèqueField, value) != true))
                {
                    this.BibliothèqueField = value;
                    this.RaisePropertyChanged("Bibliothèque");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_d_emprunt
        {
            get
            {
                return this.Date_d_empruntField;
            }
            set
            {
                if ((this.Date_d_empruntField.Equals(value) != true))
                {
                    this.Date_d_empruntField = value;
                    this.RaisePropertyChanged("Date_d_emprunt");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EMP_DateRetour
        {
            get
            {
                return this.EMP_DateRetourField;
            }
            set
            {
                if ((this.EMP_DateRetourField.Equals(value) != true))
                {
                    this.EMP_DateRetourField = value;
                    this.RaisePropertyChanged("EMP_DateRetour");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> EMP_MontantPaye
        {
            get
            {
                return this.EMP_MontantPayeField;
            }
            set
            {
                if ((this.EMP_MontantPayeField.Equals(value) != true))
                {
                    this.EMP_MontantPayeField = value;
                    this.RaisePropertyChanged("EMP_MontantPaye");
                }
            }
        }



        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LEC_GetUserData_Result", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class LEC_GetUserData_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LEC_AdresseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LEC_CodePostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LEC_DateDeNaissanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LEC_NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LEC_PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LEC_PhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LEC_PrenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LEC_SexeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LEC_UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LEC_VilleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LEC_Adresse
        {
            get
            {
                return this.LEC_AdresseField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LEC_AdresseField, value) != true))
                {
                    this.LEC_AdresseField = value;
                    this.RaisePropertyChanged("LEC_Adresse");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LEC_CodePostal
        {
            get
            {
                return this.LEC_CodePostalField;
            }
            set
            {
                if ((this.LEC_CodePostalField.Equals(value) != true))
                {
                    this.LEC_CodePostalField = value;
                    this.RaisePropertyChanged("LEC_CodePostal");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LEC_DateDeNaissance
        {
            get
            {
                return this.LEC_DateDeNaissanceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LEC_DateDeNaissanceField, value) != true))
                {
                    this.LEC_DateDeNaissanceField = value;
                    this.RaisePropertyChanged("LEC_DateDeNaissance");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LEC_Nom
        {
            get
            {
                return this.LEC_NomField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LEC_NomField, value) != true))
                {
                    this.LEC_NomField = value;
                    this.RaisePropertyChanged("LEC_Nom");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LEC_Password
        {
            get
            {
                return this.LEC_PasswordField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LEC_PasswordField, value) != true))
                {
                    this.LEC_PasswordField = value;
                    this.RaisePropertyChanged("LEC_Password");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LEC_Photo
        {
            get
            {
                return this.LEC_PhotoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LEC_PhotoField, value) != true))
                {
                    this.LEC_PhotoField = value;
                    this.RaisePropertyChanged("LEC_Photo");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LEC_Prenom
        {
            get
            {
                return this.LEC_PrenomField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LEC_PrenomField, value) != true))
                {
                    this.LEC_PrenomField = value;
                    this.RaisePropertyChanged("LEC_Prenom");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LEC_Sexe
        {
            get
            {
                return this.LEC_SexeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LEC_SexeField, value) != true))
                {
                    this.LEC_SexeField = value;
                    this.RaisePropertyChanged("LEC_Sexe");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LEC_UserName
        {
            get
            {
                return this.LEC_UserNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LEC_UserNameField, value) != true))
                {
                    this.LEC_UserNameField = value;
                    this.RaisePropertyChanged("LEC_UserName");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LEC_Ville
        {
            get
            {
                return this.LEC_VilleField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LEC_VilleField, value) != true))
                {
                    this.LEC_VilleField = value;
                    this.RaisePropertyChanged("LEC_Ville");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RES_ListeReservationsDisponibleByLEC_IdByBib_Result", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class RES_ListeReservationsDisponibleByLEC_IdByBib_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BIB_LibelleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EXE_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EXE_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LEC_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LIV_ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre
        {
            get
            {
                return this.TitreField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TitreField, value) != true))
                {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXE_Code
        {
            get
            {
                return this.EXE_CodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EXE_CodeField, value) != true))
                {
                    this.EXE_CodeField = value;
                    this.RaisePropertyChanged("EXE_Code");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BIB_Libelle
        {
            get
            {
                return this.BIB_LibelleField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BIB_LibelleField, value) != true))
                {
                    this.BIB_LibelleField = value;
                    this.RaisePropertyChanged("BIB_Libelle");
                }
            }
        }


        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EXE_Id
        {
            get
            {
                return this.EXE_IdField;
            }
            set
            {
                if ((this.EXE_IdField.Equals(value) != true))
                {
                    this.EXE_IdField = value;
                    this.RaisePropertyChanged("EXE_Id");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LEC_Id
        {
            get
            {
                return this.LEC_IdField;
            }
            set
            {
                if ((this.LEC_IdField.Equals(value) != true))
                {
                    this.LEC_IdField = value;
                    this.RaisePropertyChanged("LEC_Id");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LIV_Image
        {
            get
            {
                return this.LIV_ImageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LIV_ImageField, value) != true))
                {
                    this.LIV_ImageField = value;
                    this.RaisePropertyChanged("LIV_Image");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EMP_RetardsAllBibByLec_Result", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class EMP_RetardsAllBibByLec_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BibliothequeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_d_empruntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExemplaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_ExemplaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Jours_de_retardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LIV_ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Montant_total_du__Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Exemplaire
        {
            get
            {
                return this.ID_ExemplaireField;
            }
            set
            {
                if ((this.ID_ExemplaireField.Equals(value) != true))
                {
                    this.ID_ExemplaireField = value;
                    this.RaisePropertyChanged("ID_Exemplaire");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Exemplaire
        {
            get
            {
                return this.ExemplaireField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExemplaireField, value) != true))
                {
                    this.ExemplaireField = value;
                    this.RaisePropertyChanged("Exemplaire");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre
        {
            get
            {
                return this.TitreField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TitreField, value) != true))
                {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN
        {
            get
            {
                return this.ISBNField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ISBNField, value) != true))
                {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bibliotheque
        {
            get
            {
                return this.BibliothequeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BibliothequeField, value) != true))
                {
                    this.BibliothequeField = value;
                    this.RaisePropertyChanged("Bibliotheque");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_d_emprunt
        {
            get
            {
                return this.Date_d_empruntField;
            }
            set
            {
                if ((this.Date_d_empruntField.Equals(value) != true))
                {
                    this.Date_d_empruntField = value;
                    this.RaisePropertyChanged("Date_d_emprunt");
                }
            }
        }


        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Jours_de_retard
        {
            get
            {
                return this.Jours_de_retardField;
            }
            set
            {
                if ((this.Jours_de_retardField.Equals(value) != true))
                {
                    this.Jours_de_retardField = value;
                    this.RaisePropertyChanged("Jours_de_retard");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Montant_total_du__
        {
            get
            {
                return this.Montant_total_du__Field;
            }
            set
            {
                if ((this.Montant_total_du__Field.Equals(value) != true))
                {
                    this.Montant_total_du__Field = value;
                    this.RaisePropertyChanged("Montant_total_du__");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LIV_Image
        {
            get
            {
                return this.LIV_ImageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LIV_ImageField, value) != true))
                {
                    this.LIV_ImageField = value;
                    this.RaisePropertyChanged("LIV_Image");
                }
            }
        }


        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RES_ListeReservationsByLEC_Id_Result", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class RES_ListeReservationsByLEC_Id_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_de_réservationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_RéservationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LIV_AuteursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LIV_ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Réservation
        {
            get
            {
                return this.ID_RéservationField;
            }
            set
            {
                if ((this.ID_RéservationField.Equals(value) != true))
                {
                    this.ID_RéservationField = value;
                    this.RaisePropertyChanged("ID_Réservation");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre
        {
            get
            {
                return this.TitreField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TitreField, value) != true))
                {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN
        {
            get
            {
                return this.ISBNField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ISBNField, value) != true))
                {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_de_réservation
        {
            get
            {
                return this.Date_de_réservationField;
            }
            set
            {
                if ((this.Date_de_réservationField.Equals(value) != true))
                {
                    this.Date_de_réservationField = value;
                    this.RaisePropertyChanged("Date_de_réservation");
                }
            }
        }


        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LIV_Auteurs
        {
            get
            {
                return this.LIV_AuteursField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LIV_AuteursField, value) != true))
                {
                    this.LIV_AuteursField = value;
                    this.RaisePropertyChanged("LIV_Auteurs");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LIV_Image
        {
            get
            {
                return this.LIV_ImageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LIV_ImageField, value) != true))
                {
                    this.LIV_ImageField = value;
                    this.RaisePropertyChanged("LIV_Image");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EMP_AllEmpruntsEnCoursByLEC_Id_Result", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class EMP_AllEmpruntsEnCoursByLEC_Id_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BIB_LibelleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EMP_DateEmpruntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EXE_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LIV_ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LIV_TitreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RetardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TAR_EmpruntField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXE_Code
        {
            get
            {
                return this.EXE_CodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EXE_CodeField, value) != true))
                {
                    this.EXE_CodeField = value;
                    this.RaisePropertyChanged("EXE_Code");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LIV_Titre
        {
            get
            {
                return this.LIV_TitreField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LIV_TitreField, value) != true))
                {
                    this.LIV_TitreField = value;
                    this.RaisePropertyChanged("LIV_Titre");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BIB_Libelle
        {
            get
            {
                return this.BIB_LibelleField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BIB_LibelleField, value) != true))
                {
                    this.BIB_LibelleField = value;
                    this.RaisePropertyChanged("BIB_Libelle");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EMP_DateEmprunt
        {
            get
            {
                return this.EMP_DateEmpruntField;
            }
            set
            {
                if ((this.EMP_DateEmpruntField.Equals(value) != true))
                {
                    this.EMP_DateEmpruntField = value;
                    this.RaisePropertyChanged("EMP_DateEmprunt");
                }
            }
        }



        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LIV_Image
        {
            get
            {
                return this.LIV_ImageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LIV_ImageField, value) != true))
                {
                    this.LIV_ImageField = value;
                    this.RaisePropertyChanged("LIV_Image");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TAR_Emprunt
        {
            get
            {
                return this.TAR_EmpruntField;
            }
            set
            {
                if ((this.TAR_EmpruntField.Equals(value) != true))
                {
                    this.TAR_EmpruntField = value;
                    this.RaisePropertyChanged("TAR_Emprunt");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Retard
        {
            get
            {
                return this.RetardField;
            }
            set
            {
                if ((this.RetardField.Equals(value) != true))
                {
                    this.RetardField = value;
                    this.RaisePropertyChanged("Retard");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EXE_AllExemplairesByBibId_Result", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class EXE_AllExemplairesByBibId_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuteursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BibliothequeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExemplaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_ExemplaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LIV_ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Exemplaire
        {
            get
            {
                return this.ID_ExemplaireField;
            }
            set
            {
                if ((this.ID_ExemplaireField.Equals(value) != true))
                {
                    this.ID_ExemplaireField = value;
                    this.RaisePropertyChanged("ID_Exemplaire");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Exemplaire
        {
            get
            {
                return this.ExemplaireField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExemplaireField, value) != true))
                {
                    this.ExemplaireField = value;
                    this.RaisePropertyChanged("Exemplaire");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre
        {
            get
            {
                return this.TitreField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TitreField, value) != true))
                {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN
        {
            get
            {
                return this.ISBNField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ISBNField, value) != true))
                {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Auteurs
        {
            get
            {
                return this.AuteursField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AuteursField, value) != true))
                {
                    this.AuteursField = value;
                    this.RaisePropertyChanged("Auteurs");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bibliotheque
        {
            get
            {
                return this.BibliothequeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BibliothequeField, value) != true))
                {
                    this.BibliothequeField = value;
                    this.RaisePropertyChanged("Bibliotheque");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LIV_Image
        {
            get
            {
                return this.LIV_ImageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LIV_ImageField, value) != true))
                {
                    this.LIV_ImageField = value;
                    this.RaisePropertyChanged("LIV_Image");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EXE_AllExemplairesDispoByBibByISBN_Result", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class EXE_AllExemplairesDispoByBibByISBN_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuteursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BibliothequeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExemplaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_ExemplaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Exemplaire
        {
            get
            {
                return this.ID_ExemplaireField;
            }
            set
            {
                if ((this.ID_ExemplaireField.Equals(value) != true))
                {
                    this.ID_ExemplaireField = value;
                    this.RaisePropertyChanged("ID_Exemplaire");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Exemplaire
        {
            get
            {
                return this.ExemplaireField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExemplaireField, value) != true))
                {
                    this.ExemplaireField = value;
                    this.RaisePropertyChanged("Exemplaire");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre
        {
            get
            {
                return this.TitreField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TitreField, value) != true))
                {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN
        {
            get
            {
                return this.ISBNField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ISBNField, value) != true))
                {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Auteurs
        {
            get
            {
                return this.AuteursField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AuteursField, value) != true))
                {
                    this.AuteursField = value;
                    this.RaisePropertyChanged("Auteurs");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bibliotheque
        {
            get
            {
                return this.BibliothequeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BibliothequeField, value) != true))
                {
                    this.BibliothequeField = value;
                    this.RaisePropertyChanged("Bibliotheque");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EXE_AllExemplairesDispoByBibByTitle_Result", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class EXE_AllExemplairesDispoByBibByTitle_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuteursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BibliothèqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EXE_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExemplaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EXE_Id
        {
            get
            {
                return this.EXE_IdField;
            }
            set
            {
                if ((this.EXE_IdField.Equals(value) != true))
                {
                    this.EXE_IdField = value;
                    this.RaisePropertyChanged("EXE_Id");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Exemplaire
        {
            get
            {
                return this.ExemplaireField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExemplaireField, value) != true))
                {
                    this.ExemplaireField = value;
                    this.RaisePropertyChanged("Exemplaire");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre
        {
            get
            {
                return this.TitreField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TitreField, value) != true))
                {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN
        {
            get
            {
                return this.ISBNField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ISBNField, value) != true))
                {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Auteurs
        {
            get
            {
                return this.AuteursField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AuteursField, value) != true))
                {
                    this.AuteursField = value;
                    this.RaisePropertyChanged("Auteurs");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bibliothèque
        {
            get
            {
                return this.BibliothèqueField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BibliothèqueField, value) != true))
                {
                    this.BibliothèqueField = value;
                    this.RaisePropertyChanged("Bibliothèque");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LIV_LivreByBib_idByISBN_Result", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class LIV_LivreByBib_idByISBN_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuteursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN
        {
            get
            {
                return this.ISBNField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ISBNField, value) != true))
                {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre
        {
            get
            {
                return this.TitreField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TitreField, value) != true))
                {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image
        {
            get
            {
                return this.ImageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ImageField, value) != true))
                {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }


        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Auteurs
        {
            get
            {
                return this.AuteursField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AuteursField, value) != true))
                {
                    this.AuteursField = value;
                    this.RaisePropertyChanged("Auteurs");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LIV_LivreByBib_idByTitre_Result", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class LIV_LivreByBib_idByTitre_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuteursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN
        {
            get
            {
                return this.ISBNField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ISBNField, value) != true))
                {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre
        {
            get
            {
                return this.TitreField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TitreField, value) != true))
                {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image
        {
            get
            {
                return this.ImageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ImageField, value) != true))
                {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Auteurs
        {
            get
            {
                return this.AuteursField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AuteursField, value) != true))
                {
                    this.AuteursField = value;
                    this.RaisePropertyChanged("Auteurs");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LIV_LivreByBib_id_Result", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class LIV_LivreByBib_id_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuteursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN
        {
            get
            {
                return this.ISBNField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ISBNField, value) != true))
                {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre
        {
            get
            {
                return this.TitreField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TitreField, value) != true))
                {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image
        {
            get
            {
                return this.ImageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ImageField, value) != true))
                {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Auteurs
        {
            get
            {
                return this.AuteursField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AuteursField, value) != true))
                {
                    this.AuteursField = value;
                    this.RaisePropertyChanged("Auteurs");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceLecteur.IServiceLecteur")]
    public interface IServiceLecteur {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/BIB_AllLibelle", ReplyAction="http://tempuri.org/IServiceLecteur/BIB_AllLibelleResponse")]
        MainApp.ServiceReferenceLecteur.BIB_AllLibelle_Result[] BIB_AllLibelle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/BIB_AllLibelle", ReplyAction="http://tempuri.org/IServiceLecteur/BIB_AllLibelleResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.BIB_AllLibelle_Result[]> BIB_AllLibelleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/LEC_Login", ReplyAction="http://tempuri.org/IServiceLecteur/LEC_LoginResponse")]
        MainApp.ServiceReferenceLecteur.LEC_Login_Result LEC_Login(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/LEC_Login", ReplyAction="http://tempuri.org/IServiceLecteur/LEC_LoginResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.LEC_Login_Result> LEC_LoginAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/EMP_AllEmpruntsRenduByLEC_Id", ReplyAction="http://tempuri.org/IServiceLecteur/EMP_AllEmpruntsRenduByLEC_IdResponse")]
        MainApp.ServiceReferenceLecteur.EMP_AllEmpruntsRenduByLEC_Id_Result[] EMP_AllEmpruntsRenduByLEC_Id(int LecId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/EMP_AllEmpruntsRenduByLEC_Id", ReplyAction="http://tempuri.org/IServiceLecteur/EMP_AllEmpruntsRenduByLEC_IdResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.EMP_AllEmpruntsRenduByLEC_Id_Result[]> EMP_AllEmpruntsRenduByLEC_IdAsync(int LecId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/GetUserData", ReplyAction="http://tempuri.org/IServiceLecteur/GetUserDataResponse")]
        MainApp.ServiceReferenceLecteur.LEC_GetUserData_Result GetUserData(int lEC_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/GetUserData", ReplyAction="http://tempuri.org/IServiceLecteur/GetUserDataResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.LEC_GetUserData_Result> GetUserDataAsync(int lEC_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/LEC_UpdateUserData", ReplyAction="http://tempuri.org/IServiceLecteur/LEC_UpdateUserDataResponse")]
        int LEC_UpdateUserData(int Lec_Id, string nom, string prenom, string sexe, string adresse, string ville, int codePostal, System.DateTime dateNaissanceDateTime, string username, string password, string image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/LEC_UpdateUserData", ReplyAction="http://tempuri.org/IServiceLecteur/LEC_UpdateUserDataResponse")]
        System.Threading.Tasks.Task<int> LEC_UpdateUserDataAsync(int Lec_Id, string nom, string prenom, string sexe, string adresse, string ville, int codePostal, System.DateTime dateNaissanceDateTime, string username, string password, string image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/RES_ListeReservationsDisponibleByLEC_IdByBib", ReplyAction="http://tempuri.org/IServiceLecteur/RES_ListeReservationsDisponibleByLEC_IdByBibRe" +
            "sponse")]
        MainApp.ServiceReferenceLecteur.RES_ListeReservationsDisponibleByLEC_IdByBib_Result[] RES_ListeReservationsDisponibleByLEC_IdByBib(int lEC_Id, int bib_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/RES_ListeReservationsDisponibleByLEC_IdByBib", ReplyAction="http://tempuri.org/IServiceLecteur/RES_ListeReservationsDisponibleByLEC_IdByBibRe" +
            "sponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.RES_ListeReservationsDisponibleByLEC_IdByBib_Result[]> RES_ListeReservationsDisponibleByLEC_IdByBibAsync(int lEC_Id, int bib_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/EMP_RetardsAllBibByLec", ReplyAction="http://tempuri.org/IServiceLecteur/EMP_RetardsAllBibByLecResponse")]
        MainApp.ServiceReferenceLecteur.EMP_RetardsAllBibByLec_Result[] EMP_RetardsAllBibByLec(int lEC_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/EMP_RetardsAllBibByLec", ReplyAction="http://tempuri.org/IServiceLecteur/EMP_RetardsAllBibByLecResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.EMP_RetardsAllBibByLec_Result[]> EMP_RetardsAllBibByLecAsync(int lEC_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/RES_ListeReservationsByLEC_Id", ReplyAction="http://tempuri.org/IServiceLecteur/RES_ListeReservationsByLEC_IdResponse")]
        MainApp.ServiceReferenceLecteur.RES_ListeReservationsByLEC_Id_Result[] RES_ListeReservationsByLEC_Id(int lEC_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/RES_ListeReservationsByLEC_Id", ReplyAction="http://tempuri.org/IServiceLecteur/RES_ListeReservationsByLEC_IdResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.RES_ListeReservationsByLEC_Id_Result[]> RES_ListeReservationsByLEC_IdAsync(int lEC_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/EMP_AllEmpruntsEnCoursByLEC_Id", ReplyAction="http://tempuri.org/IServiceLecteur/EMP_AllEmpruntsEnCoursByLEC_IdResponse")]
        MainApp.ServiceReferenceLecteur.EMP_AllEmpruntsEnCoursByLEC_Id_Result[] EMP_AllEmpruntsEnCoursByLEC_Id(int lEC_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/EMP_AllEmpruntsEnCoursByLEC_Id", ReplyAction="http://tempuri.org/IServiceLecteur/EMP_AllEmpruntsEnCoursByLEC_IdResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.EMP_AllEmpruntsEnCoursByLEC_Id_Result[]> EMP_AllEmpruntsEnCoursByLEC_IdAsync(int lEC_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/EXE_AllExemplairesByBibId", ReplyAction="http://tempuri.org/IServiceLecteur/EXE_AllExemplairesByBibIdResponse")]
        MainApp.ServiceReferenceLecteur.EXE_AllExemplairesByBibId_Result[] EXE_AllExemplairesByBibId(int bib_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/EXE_AllExemplairesByBibId", ReplyAction="http://tempuri.org/IServiceLecteur/EXE_AllExemplairesByBibIdResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.EXE_AllExemplairesByBibId_Result[]> EXE_AllExemplairesByBibIdAsync(int bib_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/EXE_AllExemplairesDispoByBibByISBN", ReplyAction="http://tempuri.org/IServiceLecteur/EXE_AllExemplairesDispoByBibByISBNResponse")]
        MainApp.ServiceReferenceLecteur.EXE_AllExemplairesDispoByBibByISBN_Result[] EXE_AllExemplairesDispoByBibByISBN(int bibId, string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/EXE_AllExemplairesDispoByBibByISBN", ReplyAction="http://tempuri.org/IServiceLecteur/EXE_AllExemplairesDispoByBibByISBNResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.EXE_AllExemplairesDispoByBibByISBN_Result[]> EXE_AllExemplairesDispoByBibByISBNAsync(int bibId, string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/EXE_AllExemplairesDispoByBibByTitle", ReplyAction="http://tempuri.org/IServiceLecteur/EXE_AllExemplairesDispoByBibByTitleResponse")]
        MainApp.ServiceReferenceLecteur.EXE_AllExemplairesDispoByBibByTitle_Result[] EXE_AllExemplairesDispoByBibByTitle(int bibId, string titre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/EXE_AllExemplairesDispoByBibByTitle", ReplyAction="http://tempuri.org/IServiceLecteur/EXE_AllExemplairesDispoByBibByTitleResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.EXE_AllExemplairesDispoByBibByTitle_Result[]> EXE_AllExemplairesDispoByBibByTitleAsync(int bibId, string titre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/EXE_EmprunterExemplaire", ReplyAction="http://tempuri.org/IServiceLecteur/EXE_EmprunterExemplaireResponse")]
        int EXE_EmprunterExemplaire(int exeId, int lecId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/EXE_EmprunterExemplaire", ReplyAction="http://tempuri.org/IServiceLecteur/EXE_EmprunterExemplaireResponse")]
        System.Threading.Tasks.Task<int> EXE_EmprunterExemplaireAsync(int exeId, int lecId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/LIV_LivreByBib_idByISBN", ReplyAction="http://tempuri.org/IServiceLecteur/LIV_LivreByBib_idByISBNResponse")]
        MainApp.ServiceReferenceLecteur.LIV_LivreByBib_idByISBN_Result[] LIV_LivreByBib_idByISBN(int bibId, string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/LIV_LivreByBib_idByISBN", ReplyAction="http://tempuri.org/IServiceLecteur/LIV_LivreByBib_idByISBNResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.LIV_LivreByBib_idByISBN_Result[]> LIV_LivreByBib_idByISBNAsync(int bibId, string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/LIV_LivreByBib_idByTitre", ReplyAction="http://tempuri.org/IServiceLecteur/LIV_LivreByBib_idByTitreResponse")]
        MainApp.ServiceReferenceLecteur.LIV_LivreByBib_idByTitre_Result[] LIV_LivreByBib_idByTitre(int bibId, string titre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/LIV_LivreByBib_idByTitre", ReplyAction="http://tempuri.org/IServiceLecteur/LIV_LivreByBib_idByTitreResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.LIV_LivreByBib_idByTitre_Result[]> LIV_LivreByBib_idByTitreAsync(int bibId, string titre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/ReserverLivre", ReplyAction="http://tempuri.org/IServiceLecteur/ReserverLivreResponse")]
        int ReserverLivre(int livId, int lecId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/ReserverLivre", ReplyAction="http://tempuri.org/IServiceLecteur/ReserverLivreResponse")]
        System.Threading.Tasks.Task<int> ReserverLivreAsync(int livId, int lecId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/LIV_LivreByBib_id", ReplyAction="http://tempuri.org/IServiceLecteur/LIV_LivreByBib_idResponse")]
        MainApp.ServiceReferenceLecteur.LIV_LivreByBib_id_Result[] LIV_LivreByBib_id(int bIB_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/LIV_LivreByBib_id", ReplyAction="http://tempuri.org/IServiceLecteur/LIV_LivreByBib_idResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.LIV_LivreByBib_id_Result[]> LIV_LivreByBib_idAsync(int bIB_ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceLecteurChannel : MainApp.ServiceReferenceLecteur.IServiceLecteur, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceLecteurClient : System.ServiceModel.ClientBase<MainApp.ServiceReferenceLecteur.IServiceLecteur>, MainApp.ServiceReferenceLecteur.IServiceLecteur {
        
        public ServiceLecteurClient() {
        }
        
        public ServiceLecteurClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceLecteurClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLecteurClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLecteurClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MainApp.ServiceReferenceLecteur.BIB_AllLibelle_Result[] BIB_AllLibelle() {
            return base.Channel.BIB_AllLibelle();
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.BIB_AllLibelle_Result[]> BIB_AllLibelleAsync() {
            return base.Channel.BIB_AllLibelleAsync();
        }
        
        public MainApp.ServiceReferenceLecteur.LEC_Login_Result LEC_Login(string login, string password) {
            return base.Channel.LEC_Login(login, password);
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.LEC_Login_Result> LEC_LoginAsync(string login, string password) {
            return base.Channel.LEC_LoginAsync(login, password);
        }
        
        public MainApp.ServiceReferenceLecteur.EMP_AllEmpruntsRenduByLEC_Id_Result[] EMP_AllEmpruntsRenduByLEC_Id(int LecId) {
            return base.Channel.EMP_AllEmpruntsRenduByLEC_Id(LecId);
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.EMP_AllEmpruntsRenduByLEC_Id_Result[]> EMP_AllEmpruntsRenduByLEC_IdAsync(int LecId) {
            return base.Channel.EMP_AllEmpruntsRenduByLEC_IdAsync(LecId);
        }
        
        public MainApp.ServiceReferenceLecteur.LEC_GetUserData_Result GetUserData(int lEC_Id) {
            return base.Channel.GetUserData(lEC_Id);
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.LEC_GetUserData_Result> GetUserDataAsync(int lEC_Id) {
            return base.Channel.GetUserDataAsync(lEC_Id);
        }
        
        public int LEC_UpdateUserData(int Lec_Id, string nom, string prenom, string sexe, string adresse, string ville, int codePostal, System.DateTime dateNaissanceDateTime, string username, string password, string image) {
            return base.Channel.LEC_UpdateUserData(Lec_Id, nom, prenom, sexe, adresse, ville, codePostal, dateNaissanceDateTime, username, password, image);
        }
        
        public System.Threading.Tasks.Task<int> LEC_UpdateUserDataAsync(int Lec_Id, string nom, string prenom, string sexe, string adresse, string ville, int codePostal, System.DateTime dateNaissanceDateTime, string username, string password, string image) {
            return base.Channel.LEC_UpdateUserDataAsync(Lec_Id, nom, prenom, sexe, adresse, ville, codePostal, dateNaissanceDateTime, username, password, image);
        }
        
        public MainApp.ServiceReferenceLecteur.RES_ListeReservationsDisponibleByLEC_IdByBib_Result[] RES_ListeReservationsDisponibleByLEC_IdByBib(int lEC_Id, int bib_ID) {
            return base.Channel.RES_ListeReservationsDisponibleByLEC_IdByBib(lEC_Id, bib_ID);
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.RES_ListeReservationsDisponibleByLEC_IdByBib_Result[]> RES_ListeReservationsDisponibleByLEC_IdByBibAsync(int lEC_Id, int bib_ID) {
            return base.Channel.RES_ListeReservationsDisponibleByLEC_IdByBibAsync(lEC_Id, bib_ID);
        }
        
        public MainApp.ServiceReferenceLecteur.EMP_RetardsAllBibByLec_Result[] EMP_RetardsAllBibByLec(int lEC_Id) {
            return base.Channel.EMP_RetardsAllBibByLec(lEC_Id);
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.EMP_RetardsAllBibByLec_Result[]> EMP_RetardsAllBibByLecAsync(int lEC_Id) {
            return base.Channel.EMP_RetardsAllBibByLecAsync(lEC_Id);
        }
        
        public MainApp.ServiceReferenceLecteur.RES_ListeReservationsByLEC_Id_Result[] RES_ListeReservationsByLEC_Id(int lEC_Id) {
            return base.Channel.RES_ListeReservationsByLEC_Id(lEC_Id);
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.RES_ListeReservationsByLEC_Id_Result[]> RES_ListeReservationsByLEC_IdAsync(int lEC_Id) {
            return base.Channel.RES_ListeReservationsByLEC_IdAsync(lEC_Id);
        }
        
        public MainApp.ServiceReferenceLecteur.EMP_AllEmpruntsEnCoursByLEC_Id_Result[] EMP_AllEmpruntsEnCoursByLEC_Id(int lEC_Id) {
            return base.Channel.EMP_AllEmpruntsEnCoursByLEC_Id(lEC_Id);
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.EMP_AllEmpruntsEnCoursByLEC_Id_Result[]> EMP_AllEmpruntsEnCoursByLEC_IdAsync(int lEC_Id) {
            return base.Channel.EMP_AllEmpruntsEnCoursByLEC_IdAsync(lEC_Id);
        }
        
        public MainApp.ServiceReferenceLecteur.EXE_AllExemplairesByBibId_Result[] EXE_AllExemplairesByBibId(int bib_ID) {
            return base.Channel.EXE_AllExemplairesByBibId(bib_ID);
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.EXE_AllExemplairesByBibId_Result[]> EXE_AllExemplairesByBibIdAsync(int bib_ID) {
            return base.Channel.EXE_AllExemplairesByBibIdAsync(bib_ID);
        }
        
        public MainApp.ServiceReferenceLecteur.EXE_AllExemplairesDispoByBibByISBN_Result[] EXE_AllExemplairesDispoByBibByISBN(int bibId, string isbn) {
            return base.Channel.EXE_AllExemplairesDispoByBibByISBN(bibId, isbn);
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.EXE_AllExemplairesDispoByBibByISBN_Result[]> EXE_AllExemplairesDispoByBibByISBNAsync(int bibId, string isbn) {
            return base.Channel.EXE_AllExemplairesDispoByBibByISBNAsync(bibId, isbn);
        }
        
        public MainApp.ServiceReferenceLecteur.EXE_AllExemplairesDispoByBibByTitle_Result[] EXE_AllExemplairesDispoByBibByTitle(int bibId, string titre) {
            return base.Channel.EXE_AllExemplairesDispoByBibByTitle(bibId, titre);
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.EXE_AllExemplairesDispoByBibByTitle_Result[]> EXE_AllExemplairesDispoByBibByTitleAsync(int bibId, string titre) {
            return base.Channel.EXE_AllExemplairesDispoByBibByTitleAsync(bibId, titre);
        }
        
        public int EXE_EmprunterExemplaire(int exeId, int lecId) {
            return base.Channel.EXE_EmprunterExemplaire(exeId, lecId);
        }
        
        public System.Threading.Tasks.Task<int> EXE_EmprunterExemplaireAsync(int exeId, int lecId) {
            return base.Channel.EXE_EmprunterExemplaireAsync(exeId, lecId);
        }
        
        public MainApp.ServiceReferenceLecteur.LIV_LivreByBib_idByISBN_Result[] LIV_LivreByBib_idByISBN(int bibId, string isbn) {
            return base.Channel.LIV_LivreByBib_idByISBN(bibId, isbn);
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.LIV_LivreByBib_idByISBN_Result[]> LIV_LivreByBib_idByISBNAsync(int bibId, string isbn) {
            return base.Channel.LIV_LivreByBib_idByISBNAsync(bibId, isbn);
        }
        
        public MainApp.ServiceReferenceLecteur.LIV_LivreByBib_idByTitre_Result[] LIV_LivreByBib_idByTitre(int bibId, string titre) {
            return base.Channel.LIV_LivreByBib_idByTitre(bibId, titre);
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.LIV_LivreByBib_idByTitre_Result[]> LIV_LivreByBib_idByTitreAsync(int bibId, string titre) {
            return base.Channel.LIV_LivreByBib_idByTitreAsync(bibId, titre);
        }
        
        public int ReserverLivre(int livId, int lecId) {
            return base.Channel.ReserverLivre(livId, lecId);
        }
        
        public System.Threading.Tasks.Task<int> ReserverLivreAsync(int livId, int lecId) {
            return base.Channel.ReserverLivreAsync(livId, lecId);
        }
        
        public MainApp.ServiceReferenceLecteur.LIV_LivreByBib_id_Result[] LIV_LivreByBib_id(int bIB_ID) {
            return base.Channel.LIV_LivreByBib_id(bIB_ID);
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceLecteur.LIV_LivreByBib_id_Result[]> LIV_LivreByBib_idAsync(int bIB_ID) {
            return base.Channel.LIV_LivreByBib_idAsync(bIB_ID);
        }
    }
}
