//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainApp.ServiceReferenceAdmin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAdmin.IServiceAdmin")]
    public interface IServiceAdmin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/EXE_CreerExemplaire", ReplyAction="http://tempuri.org/IServiceAdmin/EXE_CreerExemplaireResponse")]
        void EXE_CreerExemplaire(string code, System.DateTime DateAchat, string BibLibelle, string LivTitre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/EXE_CreerExemplaire", ReplyAction="http://tempuri.org/IServiceAdmin/EXE_CreerExemplaireResponse")]
        System.Threading.Tasks.Task EXE_CreerExemplaireAsync(string code, System.DateTime DateAchat, string BibLibelle, string LivTitre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/AllExemplairesAllBib", ReplyAction="http://tempuri.org/IServiceAdmin/AllExemplairesAllBibResponse")]
        MainApp.ServiceReferenceAdmin.AllExemplairesAllBibResponse AllExemplairesAllBib(MainApp.ServiceReferenceAdmin.AllExemplairesAllBibRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/AllExemplairesAllBib", ReplyAction="http://tempuri.org/IServiceAdmin/AllExemplairesAllBibResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.AllExemplairesAllBibResponse> AllExemplairesAllBibAsync(MainApp.ServiceReferenceAdmin.AllExemplairesAllBibRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/ADM_Lgin", ReplyAction="http://tempuri.org/IServiceAdmin/ADM_LginResponse")]
        string ADM_Lgin(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/ADM_Lgin", ReplyAction="http://tempuri.org/IServiceAdmin/ADM_LginResponse")]
        System.Threading.Tasks.Task<string> ADM_LginAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/AllRetardataires", ReplyAction="http://tempuri.org/IServiceAdmin/AllRetardatairesResponse")]
        MainApp.ServiceReferenceAdmin.AllRetardatairesResponse AllRetardataires(MainApp.ServiceReferenceAdmin.AllRetardatairesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/AllRetardataires", ReplyAction="http://tempuri.org/IServiceAdmin/AllRetardatairesResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.AllRetardatairesResponse> AllRetardatairesAsync(MainApp.ServiceReferenceAdmin.AllRetardatairesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/AllLivres", ReplyAction="http://tempuri.org/IServiceAdmin/AllLivresResponse")]
        MainApp.ServiceReferenceAdmin.AllLivresResponse AllLivres(MainApp.ServiceReferenceAdmin.AllLivresRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/AllLivres", ReplyAction="http://tempuri.org/IServiceAdmin/AllLivresResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.AllLivresResponse> AllLivresAsync(MainApp.ServiceReferenceAdmin.AllLivresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/BIB_AllLibelle", ReplyAction="http://tempuri.org/IServiceAdmin/BIB_AllLibelleResponse")]
        MainApp.ServiceReferenceAdmin.BIB_AllLibelleResponse BIB_AllLibelle(MainApp.ServiceReferenceAdmin.BIB_AllLibelleRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/BIB_AllLibelle", ReplyAction="http://tempuri.org/IServiceAdmin/BIB_AllLibelleResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.BIB_AllLibelleResponse> BIB_AllLibelleAsync(MainApp.ServiceReferenceAdmin.BIB_AllLibelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/RetournerExemplaire", ReplyAction="http://tempuri.org/IServiceAdmin/RetournerExemplaireResponse")]
        void RetournerExemplaire(int exemplaireId, double montant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/RetournerExemplaire", ReplyAction="http://tempuri.org/IServiceAdmin/RetournerExemplaireResponse")]
        System.Threading.Tasks.Task RetournerExemplaireAsync(int exemplaireId, double montant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/AllLecteurs", ReplyAction="http://tempuri.org/IServiceAdmin/AllLecteursResponse")]
        MainApp.ServiceReferenceAdmin.AllLecteursResponse AllLecteurs(MainApp.ServiceReferenceAdmin.AllLecteursRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/AllLecteurs", ReplyAction="http://tempuri.org/IServiceAdmin/AllLecteursResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.AllLecteursResponse> AllLecteursAsync(MainApp.ServiceReferenceAdmin.AllLecteursRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/AllEmpruntsEnCours", ReplyAction="http://tempuri.org/IServiceAdmin/AllEmpruntsEnCoursResponse")]
        MainApp.ServiceReferenceAdmin.AllEmpruntsEnCoursResponse AllEmpruntsEnCours(MainApp.ServiceReferenceAdmin.AllEmpruntsEnCoursRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/AllEmpruntsEnCours", ReplyAction="http://tempuri.org/IServiceAdmin/AllEmpruntsEnCoursResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.AllEmpruntsEnCoursResponse> AllEmpruntsEnCoursAsync(MainApp.ServiceReferenceAdmin.AllEmpruntsEnCoursRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/LivreByISBN", ReplyAction="http://tempuri.org/IServiceAdmin/LivreByISBNResponse")]
        MainApp.ServiceReferenceAdmin.LivreByISBNResponse LivreByISBN(MainApp.ServiceReferenceAdmin.LivreByISBNRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/LivreByISBN", ReplyAction="http://tempuri.org/IServiceAdmin/LivreByISBNResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.LivreByISBNResponse> LivreByISBNAsync(MainApp.ServiceReferenceAdmin.LivreByISBNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/LivreByTitre", ReplyAction="http://tempuri.org/IServiceAdmin/LivreByTitreResponse")]
        MainApp.ServiceReferenceAdmin.LivreByTitreResponse LivreByTitre(MainApp.ServiceReferenceAdmin.LivreByTitreRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/LivreByTitre", ReplyAction="http://tempuri.org/IServiceAdmin/LivreByTitreResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.LivreByTitreResponse> LivreByTitreAsync(MainApp.ServiceReferenceAdmin.LivreByTitreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/AjoutManuelLivre", ReplyAction="http://tempuri.org/IServiceAdmin/AjoutManuelLivreResponse")]
        void AjoutManuelLivre(string ISBN, string Titre, string Image, string Auteurs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/AjoutManuelLivre", ReplyAction="http://tempuri.org/IServiceAdmin/AjoutManuelLivreResponse")]
        System.Threading.Tasks.Task AjoutManuelLivreAsync(string ISBN, string Titre, string Image, string Auteurs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/UpdateLivre", ReplyAction="http://tempuri.org/IServiceAdmin/UpdateLivreResponse")]
        void UpdateLivre(string ISBN, string Titre, string Image, string Auteurs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/UpdateLivre", ReplyAction="http://tempuri.org/IServiceAdmin/UpdateLivreResponse")]
        System.Threading.Tasks.Task UpdateLivreAsync(string ISBN, string Titre, string Image, string Auteurs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/DeleteLivre", ReplyAction="http://tempuri.org/IServiceAdmin/DeleteLivreResponse")]
        void DeleteLivre(string ISBN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/DeleteLivre", ReplyAction="http://tempuri.org/IServiceAdmin/DeleteLivreResponse")]
        System.Threading.Tasks.Task DeleteLivreAsync(string ISBN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/NbEmpruntsByLecId", ReplyAction="http://tempuri.org/IServiceAdmin/NbEmpruntsByLecIdResponse")]
        MainApp.ServiceReferenceAdmin.NbEmpruntsByLecIdResponse NbEmpruntsByLecId(MainApp.ServiceReferenceAdmin.NbEmpruntsByLecIdRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/NbEmpruntsByLecId", ReplyAction="http://tempuri.org/IServiceAdmin/NbEmpruntsByLecIdResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.NbEmpruntsByLecIdResponse> NbEmpruntsByLecIdAsync(MainApp.ServiceReferenceAdmin.NbEmpruntsByLecIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/NbRetardByLecId", ReplyAction="http://tempuri.org/IServiceAdmin/NbRetardByLecIdResponse")]
        MainApp.ServiceReferenceAdmin.NbRetardByLecIdResponse NbRetardByLecId(MainApp.ServiceReferenceAdmin.NbRetardByLecIdRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/NbRetardByLecId", ReplyAction="http://tempuri.org/IServiceAdmin/NbRetardByLecIdResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.NbRetardByLecIdResponse> NbRetardByLecIdAsync(MainApp.ServiceReferenceAdmin.NbRetardByLecIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/AllExemplairesByTitle", ReplyAction="http://tempuri.org/IServiceAdmin/AllExemplairesByTitleResponse")]
        MainApp.ServiceReferenceAdmin.AllExemplairesByTitleResponse AllExemplairesByTitle(MainApp.ServiceReferenceAdmin.AllExemplairesByTitleRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/AllExemplairesByTitle", ReplyAction="http://tempuri.org/IServiceAdmin/AllExemplairesByTitleResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.AllExemplairesByTitleResponse> AllExemplairesByTitleAsync(MainApp.ServiceReferenceAdmin.AllExemplairesByTitleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/AllExemplairesByExeCode", ReplyAction="http://tempuri.org/IServiceAdmin/AllExemplairesByExeCodeResponse")]
        MainApp.ServiceReferenceAdmin.AllExemplairesByExeCodeResponse AllExemplairesByExeCode(MainApp.ServiceReferenceAdmin.AllExemplairesByExeCodeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/AllExemplairesByExeCode", ReplyAction="http://tempuri.org/IServiceAdmin/AllExemplairesByExeCodeResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.AllExemplairesByExeCodeResponse> AllExemplairesByExeCodeAsync(MainApp.ServiceReferenceAdmin.AllExemplairesByExeCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/EXE_AllExemplaireByBIB_Libelle", ReplyAction="http://tempuri.org/IServiceAdmin/EXE_AllExemplaireByBIB_LibelleResponse")]
        MainApp.ServiceReferenceAdmin.EXE_AllExemplaireByBIB_LibelleResponse EXE_AllExemplaireByBIB_Libelle(MainApp.ServiceReferenceAdmin.EXE_AllExemplaireByBIB_LibelleRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/EXE_AllExemplaireByBIB_Libelle", ReplyAction="http://tempuri.org/IServiceAdmin/EXE_AllExemplaireByBIB_LibelleResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.EXE_AllExemplaireByBIB_LibelleResponse> EXE_AllExemplaireByBIB_LibelleAsync(MainApp.ServiceReferenceAdmin.EXE_AllExemplaireByBIB_LibelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/ChargerLivreTitres", ReplyAction="http://tempuri.org/IServiceAdmin/ChargerLivreTitresResponse")]
        MainApp.ServiceReferenceAdmin.ChargerLivreTitresResponse ChargerLivreTitres(MainApp.ServiceReferenceAdmin.ChargerLivreTitresRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdmin/ChargerLivreTitres", ReplyAction="http://tempuri.org/IServiceAdmin/ChargerLivreTitresResponse")]
        System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.ChargerLivreTitresResponse> ChargerLivreTitresAsync(MainApp.ServiceReferenceAdmin.ChargerLivreTitresRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AllExemplairesAllBib", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AllExemplairesAllBibRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet ds;
        
        public AllExemplairesAllBibRequest() {
        }
        
        public AllExemplairesAllBibRequest(System.Data.DataSet ds) {
            this.ds = ds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AllExemplairesAllBibResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AllExemplairesAllBibResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet ds;
        
        public AllExemplairesAllBibResponse() {
        }
        
        public AllExemplairesAllBibResponse(System.Data.DataSet ds) {
            this.ds = ds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AllRetardataires", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AllRetardatairesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet ds;
        
        public AllRetardatairesRequest() {
        }
        
        public AllRetardatairesRequest(System.Data.DataSet ds) {
            this.ds = ds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AllRetardatairesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AllRetardatairesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet ds;
        
        public AllRetardatairesResponse() {
        }
        
        public AllRetardatairesResponse(System.Data.DataSet ds) {
            this.ds = ds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AllLivres", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AllLivresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet ds;
        
        public AllLivresRequest() {
        }
        
        public AllLivresRequest(System.Data.DataSet ds) {
            this.ds = ds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AllLivresResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AllLivresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet ds;
        
        public AllLivresResponse() {
        }
        
        public AllLivresResponse(System.Data.DataSet ds) {
            this.ds = ds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BIB_AllLibelle", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BIB_AllLibelleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] bibliotheques;
        
        public BIB_AllLibelleRequest() {
        }
        
        public BIB_AllLibelleRequest(string[] bibliotheques) {
            this.bibliotheques = bibliotheques;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BIB_AllLibelleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BIB_AllLibelleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] bibliotheques;
        
        public BIB_AllLibelleResponse() {
        }
        
        public BIB_AllLibelleResponse(string[] bibliotheques) {
            this.bibliotheques = bibliotheques;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AllLecteurs", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AllLecteursRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet ds;
        
        public AllLecteursRequest() {
        }
        
        public AllLecteursRequest(System.Data.DataSet ds) {
            this.ds = ds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AllLecteursResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AllLecteursResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet ds;
        
        public AllLecteursResponse() {
        }
        
        public AllLecteursResponse(System.Data.DataSet ds) {
            this.ds = ds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AllEmpruntsEnCours", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AllEmpruntsEnCoursRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet ds;
        
        public AllEmpruntsEnCoursRequest() {
        }
        
        public AllEmpruntsEnCoursRequest(System.Data.DataSet ds) {
            this.ds = ds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AllEmpruntsEnCoursResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AllEmpruntsEnCoursResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet ds;
        
        public AllEmpruntsEnCoursResponse() {
        }
        
        public AllEmpruntsEnCoursResponse(System.Data.DataSet ds) {
            this.ds = ds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LivreByISBN", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LivreByISBNRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet ds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string isbn;
        
        public LivreByISBNRequest() {
        }
        
        public LivreByISBNRequest(System.Data.DataSet ds, string isbn) {
            this.ds = ds;
            this.isbn = isbn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LivreByISBNResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LivreByISBNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet ds;
        
        public LivreByISBNResponse() {
        }
        
        public LivreByISBNResponse(System.Data.DataSet ds) {
            this.ds = ds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LivreByTitre", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LivreByTitreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet ds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string titre;
        
        public LivreByTitreRequest() {
        }
        
        public LivreByTitreRequest(System.Data.DataSet ds, string titre) {
            this.ds = ds;
            this.titre = titre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LivreByTitreResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LivreByTitreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet ds;
        
        public LivreByTitreResponse() {
        }
        
        public LivreByTitreResponse(System.Data.DataSet ds) {
            this.ds = ds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NbEmpruntsByLecId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NbEmpruntsByLecIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int nbreEmprunts;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int LecId;
        
        public NbEmpruntsByLecIdRequest() {
        }
        
        public NbEmpruntsByLecIdRequest(int nbreEmprunts, int LecId) {
            this.nbreEmprunts = nbreEmprunts;
            this.LecId = LecId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NbEmpruntsByLecIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NbEmpruntsByLecIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int nbreEmprunts;
        
        public NbEmpruntsByLecIdResponse() {
        }
        
        public NbEmpruntsByLecIdResponse(int nbreEmprunts) {
            this.nbreEmprunts = nbreEmprunts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NbRetardByLecId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NbRetardByLecIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int nbRetards;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int LecId;
        
        public NbRetardByLecIdRequest() {
        }
        
        public NbRetardByLecIdRequest(int nbRetards, int LecId) {
            this.nbRetards = nbRetards;
            this.LecId = LecId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NbRetardByLecIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NbRetardByLecIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int nbRetards;
        
        public NbRetardByLecIdResponse() {
        }
        
        public NbRetardByLecIdResponse(int nbRetards) {
            this.nbRetards = nbRetards;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AllExemplairesByTitle", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AllExemplairesByTitleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet ds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Title;
        
        public AllExemplairesByTitleRequest() {
        }
        
        public AllExemplairesByTitleRequest(System.Data.DataSet ds, string Title) {
            this.ds = ds;
            this.Title = Title;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AllExemplairesByTitleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AllExemplairesByTitleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet ds;
        
        public AllExemplairesByTitleResponse() {
        }
        
        public AllExemplairesByTitleResponse(System.Data.DataSet ds) {
            this.ds = ds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AllExemplairesByExeCode", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AllExemplairesByExeCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet ds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ExeCode;
        
        public AllExemplairesByExeCodeRequest() {
        }
        
        public AllExemplairesByExeCodeRequest(System.Data.DataSet ds, string ExeCode) {
            this.ds = ds;
            this.ExeCode = ExeCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AllExemplairesByExeCodeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AllExemplairesByExeCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet ds;
        
        public AllExemplairesByExeCodeResponse() {
        }
        
        public AllExemplairesByExeCodeResponse(System.Data.DataSet ds) {
            this.ds = ds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EXE_AllExemplaireByBIB_Libelle", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EXE_AllExemplaireByBIB_LibelleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable dt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Libelle;
        
        public EXE_AllExemplaireByBIB_LibelleRequest() {
        }
        
        public EXE_AllExemplaireByBIB_LibelleRequest(System.Data.DataTable dt, string Libelle) {
            this.dt = dt;
            this.Libelle = Libelle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EXE_AllExemplaireByBIB_LibelleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EXE_AllExemplaireByBIB_LibelleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable dt;
        
        public EXE_AllExemplaireByBIB_LibelleResponse() {
        }
        
        public EXE_AllExemplaireByBIB_LibelleResponse(System.Data.DataTable dt) {
            this.dt = dt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChargerLivreTitres", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChargerLivreTitresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] titres;
        
        public ChargerLivreTitresRequest() {
        }
        
        public ChargerLivreTitresRequest(string[] titres) {
            this.titres = titres;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChargerLivreTitresResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChargerLivreTitresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] titres;
        
        public ChargerLivreTitresResponse() {
        }
        
        public ChargerLivreTitresResponse(string[] titres) {
            this.titres = titres;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAdminChannel : MainApp.ServiceReferenceAdmin.IServiceAdmin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAdminClient : System.ServiceModel.ClientBase<MainApp.ServiceReferenceAdmin.IServiceAdmin>, MainApp.ServiceReferenceAdmin.IServiceAdmin {
        
        public ServiceAdminClient() {
        }
        
        public ServiceAdminClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAdminClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAdminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAdminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void EXE_CreerExemplaire(string code, System.DateTime DateAchat, string BibLibelle, string LivTitre) {
            base.Channel.EXE_CreerExemplaire(code, DateAchat, BibLibelle, LivTitre);
        }
        
        public System.Threading.Tasks.Task EXE_CreerExemplaireAsync(string code, System.DateTime DateAchat, string BibLibelle, string LivTitre) {
            return base.Channel.EXE_CreerExemplaireAsync(code, DateAchat, BibLibelle, LivTitre);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainApp.ServiceReferenceAdmin.AllExemplairesAllBibResponse MainApp.ServiceReferenceAdmin.IServiceAdmin.AllExemplairesAllBib(MainApp.ServiceReferenceAdmin.AllExemplairesAllBibRequest request) {
            return base.Channel.AllExemplairesAllBib(request);
        }
        
        public void AllExemplairesAllBib(ref System.Data.DataSet ds) {
            MainApp.ServiceReferenceAdmin.AllExemplairesAllBibRequest inValue = new MainApp.ServiceReferenceAdmin.AllExemplairesAllBibRequest();
            inValue.ds = ds;
            MainApp.ServiceReferenceAdmin.AllExemplairesAllBibResponse retVal = ((MainApp.ServiceReferenceAdmin.IServiceAdmin)(this)).AllExemplairesAllBib(inValue);
            ds = retVal.ds;
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.AllExemplairesAllBibResponse> AllExemplairesAllBibAsync(MainApp.ServiceReferenceAdmin.AllExemplairesAllBibRequest request) {
            return base.Channel.AllExemplairesAllBibAsync(request);
        }
        
        public string ADM_Lgin(string userName, string password) {
            return base.Channel.ADM_Lgin(userName, password);
        }
        
        public System.Threading.Tasks.Task<string> ADM_LginAsync(string userName, string password) {
            return base.Channel.ADM_LginAsync(userName, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainApp.ServiceReferenceAdmin.AllRetardatairesResponse MainApp.ServiceReferenceAdmin.IServiceAdmin.AllRetardataires(MainApp.ServiceReferenceAdmin.AllRetardatairesRequest request) {
            return base.Channel.AllRetardataires(request);
        }
        
        public void AllRetardataires(ref System.Data.DataSet ds) {
            MainApp.ServiceReferenceAdmin.AllRetardatairesRequest inValue = new MainApp.ServiceReferenceAdmin.AllRetardatairesRequest();
            inValue.ds = ds;
            MainApp.ServiceReferenceAdmin.AllRetardatairesResponse retVal = ((MainApp.ServiceReferenceAdmin.IServiceAdmin)(this)).AllRetardataires(inValue);
            ds = retVal.ds;
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.AllRetardatairesResponse> AllRetardatairesAsync(MainApp.ServiceReferenceAdmin.AllRetardatairesRequest request) {
            return base.Channel.AllRetardatairesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainApp.ServiceReferenceAdmin.AllLivresResponse MainApp.ServiceReferenceAdmin.IServiceAdmin.AllLivres(MainApp.ServiceReferenceAdmin.AllLivresRequest request) {
            return base.Channel.AllLivres(request);
        }
        
        public void AllLivres(ref System.Data.DataSet ds) {
            MainApp.ServiceReferenceAdmin.AllLivresRequest inValue = new MainApp.ServiceReferenceAdmin.AllLivresRequest();
            inValue.ds = ds;
            MainApp.ServiceReferenceAdmin.AllLivresResponse retVal = ((MainApp.ServiceReferenceAdmin.IServiceAdmin)(this)).AllLivres(inValue);
            ds = retVal.ds;
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.AllLivresResponse> AllLivresAsync(MainApp.ServiceReferenceAdmin.AllLivresRequest request) {
            return base.Channel.AllLivresAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainApp.ServiceReferenceAdmin.BIB_AllLibelleResponse MainApp.ServiceReferenceAdmin.IServiceAdmin.BIB_AllLibelle(MainApp.ServiceReferenceAdmin.BIB_AllLibelleRequest request) {
            return base.Channel.BIB_AllLibelle(request);
        }
        
        public void BIB_AllLibelle(ref string[] bibliotheques) {
            MainApp.ServiceReferenceAdmin.BIB_AllLibelleRequest inValue = new MainApp.ServiceReferenceAdmin.BIB_AllLibelleRequest();
            inValue.bibliotheques = bibliotheques;
            MainApp.ServiceReferenceAdmin.BIB_AllLibelleResponse retVal = ((MainApp.ServiceReferenceAdmin.IServiceAdmin)(this)).BIB_AllLibelle(inValue);
            bibliotheques = retVal.bibliotheques;
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.BIB_AllLibelleResponse> BIB_AllLibelleAsync(MainApp.ServiceReferenceAdmin.BIB_AllLibelleRequest request) {
            return base.Channel.BIB_AllLibelleAsync(request);
        }
        
        public void RetournerExemplaire(int exemplaireId, double montant) {
            base.Channel.RetournerExemplaire(exemplaireId, montant);
        }
        
        public System.Threading.Tasks.Task RetournerExemplaireAsync(int exemplaireId, double montant) {
            return base.Channel.RetournerExemplaireAsync(exemplaireId, montant);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainApp.ServiceReferenceAdmin.AllLecteursResponse MainApp.ServiceReferenceAdmin.IServiceAdmin.AllLecteurs(MainApp.ServiceReferenceAdmin.AllLecteursRequest request) {
            return base.Channel.AllLecteurs(request);
        }
        
        public void AllLecteurs(ref System.Data.DataSet ds) {
            MainApp.ServiceReferenceAdmin.AllLecteursRequest inValue = new MainApp.ServiceReferenceAdmin.AllLecteursRequest();
            inValue.ds = ds;
            MainApp.ServiceReferenceAdmin.AllLecteursResponse retVal = ((MainApp.ServiceReferenceAdmin.IServiceAdmin)(this)).AllLecteurs(inValue);
            ds = retVal.ds;
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.AllLecteursResponse> AllLecteursAsync(MainApp.ServiceReferenceAdmin.AllLecteursRequest request) {
            return base.Channel.AllLecteursAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainApp.ServiceReferenceAdmin.AllEmpruntsEnCoursResponse MainApp.ServiceReferenceAdmin.IServiceAdmin.AllEmpruntsEnCours(MainApp.ServiceReferenceAdmin.AllEmpruntsEnCoursRequest request) {
            return base.Channel.AllEmpruntsEnCours(request);
        }
        
        public void AllEmpruntsEnCours(ref System.Data.DataSet ds) {
            MainApp.ServiceReferenceAdmin.AllEmpruntsEnCoursRequest inValue = new MainApp.ServiceReferenceAdmin.AllEmpruntsEnCoursRequest();
            inValue.ds = ds;
            MainApp.ServiceReferenceAdmin.AllEmpruntsEnCoursResponse retVal = ((MainApp.ServiceReferenceAdmin.IServiceAdmin)(this)).AllEmpruntsEnCours(inValue);
            ds = retVal.ds;
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.AllEmpruntsEnCoursResponse> AllEmpruntsEnCoursAsync(MainApp.ServiceReferenceAdmin.AllEmpruntsEnCoursRequest request) {
            return base.Channel.AllEmpruntsEnCoursAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainApp.ServiceReferenceAdmin.LivreByISBNResponse MainApp.ServiceReferenceAdmin.IServiceAdmin.LivreByISBN(MainApp.ServiceReferenceAdmin.LivreByISBNRequest request) {
            return base.Channel.LivreByISBN(request);
        }
        
        public void LivreByISBN(ref System.Data.DataSet ds, string isbn) {
            MainApp.ServiceReferenceAdmin.LivreByISBNRequest inValue = new MainApp.ServiceReferenceAdmin.LivreByISBNRequest();
            inValue.ds = ds;
            inValue.isbn = isbn;
            MainApp.ServiceReferenceAdmin.LivreByISBNResponse retVal = ((MainApp.ServiceReferenceAdmin.IServiceAdmin)(this)).LivreByISBN(inValue);
            ds = retVal.ds;
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.LivreByISBNResponse> LivreByISBNAsync(MainApp.ServiceReferenceAdmin.LivreByISBNRequest request) {
            return base.Channel.LivreByISBNAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainApp.ServiceReferenceAdmin.LivreByTitreResponse MainApp.ServiceReferenceAdmin.IServiceAdmin.LivreByTitre(MainApp.ServiceReferenceAdmin.LivreByTitreRequest request) {
            return base.Channel.LivreByTitre(request);
        }
        
        public void LivreByTitre(ref System.Data.DataSet ds, string titre) {
            MainApp.ServiceReferenceAdmin.LivreByTitreRequest inValue = new MainApp.ServiceReferenceAdmin.LivreByTitreRequest();
            inValue.ds = ds;
            inValue.titre = titre;
            MainApp.ServiceReferenceAdmin.LivreByTitreResponse retVal = ((MainApp.ServiceReferenceAdmin.IServiceAdmin)(this)).LivreByTitre(inValue);
            ds = retVal.ds;
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.LivreByTitreResponse> LivreByTitreAsync(MainApp.ServiceReferenceAdmin.LivreByTitreRequest request) {
            return base.Channel.LivreByTitreAsync(request);
        }
        
        public void AjoutManuelLivre(string ISBN, string Titre, string Image, string Auteurs) {
            base.Channel.AjoutManuelLivre(ISBN, Titre, Image, Auteurs);
        }
        
        public System.Threading.Tasks.Task AjoutManuelLivreAsync(string ISBN, string Titre, string Image, string Auteurs) {
            return base.Channel.AjoutManuelLivreAsync(ISBN, Titre, Image, Auteurs);
        }
        
        public void UpdateLivre(string ISBN, string Titre, string Image, string Auteurs) {
            base.Channel.UpdateLivre(ISBN, Titre, Image, Auteurs);
        }
        
        public System.Threading.Tasks.Task UpdateLivreAsync(string ISBN, string Titre, string Image, string Auteurs) {
            return base.Channel.UpdateLivreAsync(ISBN, Titre, Image, Auteurs);
        }
        
        public void DeleteLivre(string ISBN) {
            base.Channel.DeleteLivre(ISBN);
        }
        
        public System.Threading.Tasks.Task DeleteLivreAsync(string ISBN) {
            return base.Channel.DeleteLivreAsync(ISBN);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainApp.ServiceReferenceAdmin.NbEmpruntsByLecIdResponse MainApp.ServiceReferenceAdmin.IServiceAdmin.NbEmpruntsByLecId(MainApp.ServiceReferenceAdmin.NbEmpruntsByLecIdRequest request) {
            return base.Channel.NbEmpruntsByLecId(request);
        }
        
        public void NbEmpruntsByLecId(ref int nbreEmprunts, int LecId) {
            MainApp.ServiceReferenceAdmin.NbEmpruntsByLecIdRequest inValue = new MainApp.ServiceReferenceAdmin.NbEmpruntsByLecIdRequest();
            inValue.nbreEmprunts = nbreEmprunts;
            inValue.LecId = LecId;
            MainApp.ServiceReferenceAdmin.NbEmpruntsByLecIdResponse retVal = ((MainApp.ServiceReferenceAdmin.IServiceAdmin)(this)).NbEmpruntsByLecId(inValue);
            nbreEmprunts = retVal.nbreEmprunts;
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.NbEmpruntsByLecIdResponse> NbEmpruntsByLecIdAsync(MainApp.ServiceReferenceAdmin.NbEmpruntsByLecIdRequest request) {
            return base.Channel.NbEmpruntsByLecIdAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainApp.ServiceReferenceAdmin.NbRetardByLecIdResponse MainApp.ServiceReferenceAdmin.IServiceAdmin.NbRetardByLecId(MainApp.ServiceReferenceAdmin.NbRetardByLecIdRequest request) {
            return base.Channel.NbRetardByLecId(request);
        }
        
        public void NbRetardByLecId(ref int nbRetards, int LecId) {
            MainApp.ServiceReferenceAdmin.NbRetardByLecIdRequest inValue = new MainApp.ServiceReferenceAdmin.NbRetardByLecIdRequest();
            inValue.nbRetards = nbRetards;
            inValue.LecId = LecId;
            MainApp.ServiceReferenceAdmin.NbRetardByLecIdResponse retVal = ((MainApp.ServiceReferenceAdmin.IServiceAdmin)(this)).NbRetardByLecId(inValue);
            nbRetards = retVal.nbRetards;
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.NbRetardByLecIdResponse> NbRetardByLecIdAsync(MainApp.ServiceReferenceAdmin.NbRetardByLecIdRequest request) {
            return base.Channel.NbRetardByLecIdAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainApp.ServiceReferenceAdmin.AllExemplairesByTitleResponse MainApp.ServiceReferenceAdmin.IServiceAdmin.AllExemplairesByTitle(MainApp.ServiceReferenceAdmin.AllExemplairesByTitleRequest request) {
            return base.Channel.AllExemplairesByTitle(request);
        }
        
        public void AllExemplairesByTitle(ref System.Data.DataSet ds, string Title) {
            MainApp.ServiceReferenceAdmin.AllExemplairesByTitleRequest inValue = new MainApp.ServiceReferenceAdmin.AllExemplairesByTitleRequest();
            inValue.ds = ds;
            inValue.Title = Title;
            MainApp.ServiceReferenceAdmin.AllExemplairesByTitleResponse retVal = ((MainApp.ServiceReferenceAdmin.IServiceAdmin)(this)).AllExemplairesByTitle(inValue);
            ds = retVal.ds;
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.AllExemplairesByTitleResponse> AllExemplairesByTitleAsync(MainApp.ServiceReferenceAdmin.AllExemplairesByTitleRequest request) {
            return base.Channel.AllExemplairesByTitleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainApp.ServiceReferenceAdmin.AllExemplairesByExeCodeResponse MainApp.ServiceReferenceAdmin.IServiceAdmin.AllExemplairesByExeCode(MainApp.ServiceReferenceAdmin.AllExemplairesByExeCodeRequest request) {
            return base.Channel.AllExemplairesByExeCode(request);
        }
        
        public void AllExemplairesByExeCode(ref System.Data.DataSet ds, string ExeCode) {
            MainApp.ServiceReferenceAdmin.AllExemplairesByExeCodeRequest inValue = new MainApp.ServiceReferenceAdmin.AllExemplairesByExeCodeRequest();
            inValue.ds = ds;
            inValue.ExeCode = ExeCode;
            MainApp.ServiceReferenceAdmin.AllExemplairesByExeCodeResponse retVal = ((MainApp.ServiceReferenceAdmin.IServiceAdmin)(this)).AllExemplairesByExeCode(inValue);
            ds = retVal.ds;
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.AllExemplairesByExeCodeResponse> AllExemplairesByExeCodeAsync(MainApp.ServiceReferenceAdmin.AllExemplairesByExeCodeRequest request) {
            return base.Channel.AllExemplairesByExeCodeAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainApp.ServiceReferenceAdmin.EXE_AllExemplaireByBIB_LibelleResponse MainApp.ServiceReferenceAdmin.IServiceAdmin.EXE_AllExemplaireByBIB_Libelle(MainApp.ServiceReferenceAdmin.EXE_AllExemplaireByBIB_LibelleRequest request) {
            return base.Channel.EXE_AllExemplaireByBIB_Libelle(request);
        }
        
        public void EXE_AllExemplaireByBIB_Libelle(ref System.Data.DataTable dt, string Libelle) {
            MainApp.ServiceReferenceAdmin.EXE_AllExemplaireByBIB_LibelleRequest inValue = new MainApp.ServiceReferenceAdmin.EXE_AllExemplaireByBIB_LibelleRequest();
            inValue.dt = dt;
            inValue.Libelle = Libelle;
            MainApp.ServiceReferenceAdmin.EXE_AllExemplaireByBIB_LibelleResponse retVal = ((MainApp.ServiceReferenceAdmin.IServiceAdmin)(this)).EXE_AllExemplaireByBIB_Libelle(inValue);
            dt = retVal.dt;
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.EXE_AllExemplaireByBIB_LibelleResponse> EXE_AllExemplaireByBIB_LibelleAsync(MainApp.ServiceReferenceAdmin.EXE_AllExemplaireByBIB_LibelleRequest request) {
            return base.Channel.EXE_AllExemplaireByBIB_LibelleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainApp.ServiceReferenceAdmin.ChargerLivreTitresResponse MainApp.ServiceReferenceAdmin.IServiceAdmin.ChargerLivreTitres(MainApp.ServiceReferenceAdmin.ChargerLivreTitresRequest request) {
            return base.Channel.ChargerLivreTitres(request);
        }
        
        public void ChargerLivreTitres(ref string[] titres) {
            MainApp.ServiceReferenceAdmin.ChargerLivreTitresRequest inValue = new MainApp.ServiceReferenceAdmin.ChargerLivreTitresRequest();
            inValue.titres = titres;
            MainApp.ServiceReferenceAdmin.ChargerLivreTitresResponse retVal = ((MainApp.ServiceReferenceAdmin.IServiceAdmin)(this)).ChargerLivreTitres(inValue);
            titres = retVal.titres;
        }
        
        public System.Threading.Tasks.Task<MainApp.ServiceReferenceAdmin.ChargerLivreTitresResponse> ChargerLivreTitresAsync(MainApp.ServiceReferenceAdmin.ChargerLivreTitresRequest request) {
            return base.Channel.ChargerLivreTitresAsync(request);
        }
    }
}
