//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int RES_Id { get; set; }
        public System.DateTime RES_DateReservation { get; set; }
        public Nullable<bool> RES_Supprimee { get; set; }
        public int LEC_Id { get; set; }
        public int LIV_Id { get; set; }
    
        public virtual Lecteur Lecteur { get; set; }
        public virtual Livre Livre { get; set; }
    }
}
