//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exemplaire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exemplaire()
        {
            this.Emprunt = new HashSet<Emprunt>();
        }
    
        public int EXE_Id { get; set; }
        public string EXE_Code { get; set; }
        public string EXE_DateAchat { get; set; }
        public Nullable<bool> EXE_Indisponible { get; set; }
        public int BIB_ID { get; set; }
        public int LIV_Id { get; set; }
    
        public virtual Bibliotheque Bibliotheque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emprunt> Emprunt { get; set; }
        public virtual Livre Livre { get; set; }
    }
}
